In [123]:
import pandas as pd

In [124]:
#reading the data frame
email = pd.read_csv('contacts.csv')
email

,Company Name,URL,Contact,First Name,Last Name,Email
0,All In One Security,all-in-one-security.com,Josh Armstrong,Josh,Armstrong,josh.armstrong@aiosecurity.com
1,All In One Security,all-in-one-security.com,Paul Jr Cox Sr.,Paul,Jr Cox Sr.,NaN
2,ALL4,allinc.com,Kristiaan Wiedegreen,Kristiaan,Wiedegreen,NaN
3,ALL4,allinc.com,Michael Gach,Michael,Gach,NaN
4,Alarm Brokers,alarmbrokers.net,Ashley Newsom,Ashley,Newsom,NaN
...,...,...,...,...,...,...
998,Construction Equipment & Supply,ces-co.net,Jeff Bryant,Jeff,Bryant,NaN
999,Construction Equipment & Supply,ces-co.net,Paul Newland,Paul,Newland,NaN
1000,Construction Equipment & Supply,ces-co.net,Randy Fulmer,Randy,Fulmer,NaN
1001,Construction Equipment & Supply,ces-co.net,Edward Cordova,Edward,Cordova,NaN
1002,Construction Equipment & Supply,ces-co.net,Billie Bryant Schultz,Billie,Bryant Schultz,NaN

In [125]:
#importing some packages
from string import punctuation

In [126]:
#check out what the package includes
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [127]:
#defined the get_punct fucntion, that takes email prefix and returns the punctuiation is one is found
def get_punct(email_prefix):
    punct_return = None
    
    for punct in punctuation:
        if punct in email_prefix:
            punct_return = punct
            break
        
    return punct_return

In [128]:
#testing if the function works 
email_prefix = 'emil.bobev'

get_punct(email_prefix)

'.'

In [129]:
# find all possible patterns
def pattern_match(first, last, email):
    first_name = first.lower()
    last_name = last.lower() 
    
    if type(email) == float: 
        return 'Email is Empty'
    
    email_prefix = email.split('@')[0].lower()
    domain = email.split('@')[1].lower()
    punct = get_punct(email_prefix)
    
    

    if punct:
        if first_name == email_prefix[:len(first)] and last_name == email_prefix[-len(last):]:
            return {'pattern_match': 'first_name_last_name','punct': punct, 'domain': domain}
        elif first_name != email_prefix[:len(first)] and last_name == email_prefix[-len(last):] and first_name[0] == email_prefix.split(punct)[0]:
            return {'pattern_match': 'first_initial_last_name','punct': punct, 'domain': domain}
        elif first_name == email_prefix[:len(first)] and last_name != email_prefix[-len(last):] and last_name[0] == email_prefix.split(punct)[1]:
            return {'pattern_match': 'first_name_last_initial','punct': punct, 'domain': domain}
        elif last_name == email_prefix[:len(last)] and first_name[0] == email_prefix.split(punct)[1]:
            return {'pattern_match': 'last_name_first_initial','punct': punct, 'domain': domain}
        elif last_name[0] == email_prefix.split(punct)[0]  and first_name == email_prefix.split(punct)[1]:
            return {'pattern_match': 'last_initial_first_name','punct': punct, 'domain': domain}
        elif last_name == email_prefix.split(punct)[0]  and first_name == email_prefix.split(punct)[1]:
            return {'pattern_match': 'last_name_first_name','punct': punct, 'domain': domain}
        
        else:
            return 'Email given, pattern not found'
    
    else: 
        if first_name == email_prefix[:len(first)] and last_name == email_prefix[-len(last):]:
            return {'pattern_match': 'first_name_last_name','punct': punct, 'domain': domain}
        elif first_name[0] == email_prefix[0] and last_name == email_prefix[-len(last):] and len(last_name) + 1 == len(email_prefix):
            return {'pattern_match': 'first_initial_last_name','punct': punct, 'domain': domain}
        elif first_name == email_prefix[:len(first)] and last_name[0] == email_prefix[-1] and len(first_name) + 1 == len(email_prefix):
            return {'pattern_match': 'first_name_last_initial','punct': punct, 'domain': domain}
        elif last_name == email_prefix[:len(last)] and first_name[0] == email_prefix[-1] and len(last_name) +1 == len(email_prefix):
            return {'pattern_match': 'last_name_first_initial','punct': punct, 'domain': domain}
        elif last_name[0] == email_prefix[0]  and first_name == email_prefix[1:]:
            return {'pattern_match': 'last_initial_first_name','punct': punct, 'domain': domain}
        elif last_name == email_prefix[:len(last)]  and first_name == email_prefix[-len(first):] and len(email_prefix) == len(first_name)+ len(last_name):
            return {'pattern_match': 'last_name_first_name','punct': punct, 'domain': domain}
        elif email_prefix == first_name :
            return {'pattern_match': 'first_name','punct': punct, 'domain': domain}
        elif email_prefix == last_name:
            return {'pattern_match': 'last_name','punct': punct, 'domain': domain}
        
        else:
            return 'Email given, pattern not found'
        

pattern_match ('Emil','Bobev', 'bobev@stockton.edu')

{'pattern_match': 'last_name', 'punct': None, 'domain': 'stockton.edu'}

In [130]:
#create a dataframe email2 which creates a pattern_match column
email['pattern_match'] = email[["First Name","Last Name", "Email"]].apply(lambda x: pattern_match(*x), axis=1)
email

,Company Name,URL,Contact,First Name,Last Name,Email,pattern_match
0,All In One Security,all-in-one-security.com,Josh Armstrong,Josh,Armstrong,josh.armstrong@aiosecurity.com,"{'pattern_match': 'first_name_last_name', 'pun..."
1,All In One Security,all-in-one-security.com,Paul Jr Cox Sr.,Paul,Jr Cox Sr.,NaN,Email is Empty
2,ALL4,allinc.com,Kristiaan Wiedegreen,Kristiaan,Wiedegreen,NaN,Email is Empty
3,ALL4,allinc.com,Michael Gach,Michael,Gach,NaN,Email is Empty
4,Alarm Brokers,alarmbrokers.net,Ashley Newsom,Ashley,Newsom,NaN,Email is Empty
...,...,...,...,...,...,...,...
998,Construction Equipment & Supply,ces-co.net,Jeff Bryant,Jeff,Bryant,NaN,Email is Empty
999,Construction Equipment & Supply,ces-co.net,Paul Newland,Paul,Newland,NaN,Email is Empty
1000,Construction Equipment & Supply,ces-co.net,Randy Fulmer,Randy,Fulmer,NaN,Email is Empty
1001,Construction Equipment & Supply,ces-co.net,Edward Cordova,Edward,Cordova,NaN,Email is Empty
1002,Construction Equipment & Supply,ces-co.net,Billie Bryant Schultz,Billie,Bryant Schultz,NaN,Email is Empty

In [131]:
#modifiing the dataframe so it breaks it down and displays patter, punctuation and checker(how the email is created - pattern + url)
email['pattern'] = email.apply(lambda _: '',axis=1)
email['punctuation'] = email.apply(lambda _: '',axis=1)
email['domain'] = email.apply(lambda _: '',axis=1)
email['checker'] = email.apply(lambda _: '',axis=1)

for index, row in email.iterrows():
    pattern = row['pattern_match']
    if type(pattern) == dict: 
        row['pattern']=pattern.get('pattern_match')
        row['punctuation']=pattern.get('punct')
        row['domain']=pattern.get('domain')
        row['checker']= pattern.get('pattern_match') + str(pattern.get('punct')) + pattern.get('domain')
    else: 
        row['pattern']='pass'
        row['punctuation']='pass'
        row['domain']='pass'
        row['checker'] = 'pass'
        
email

,Company Name,URL,Contact,First Name,Last Name,Email,pattern_match,pattern,punctuation,domain,checker
0,All In One Security,all-in-one-security.com,Josh Armstrong,Josh,Armstrong,josh.armstrong@aiosecurity.com,"{'pattern_match': 'first_name_last_name', 'pun...",first_name_last_name,.,aiosecurity.com,first_name_last_name.aiosecurity.com
1,All In One Security,all-in-one-security.com,Paul Jr Cox Sr.,Paul,Jr Cox Sr.,NaN,Email is Empty,pass,pass,pass,pass
2,ALL4,allinc.com,Kristiaan Wiedegreen,Kristiaan,Wiedegreen,NaN,Email is Empty,pass,pass,pass,pass
3,ALL4,allinc.com,Michael Gach,Michael,Gach,NaN,Email is Empty,pass,pass,pass,pass
4,Alarm Brokers,alarmbrokers.net,Ashley Newsom,Ashley,Newsom,NaN,Email is Empty,pass,pass,pass,pass
...,...,...,...,...,...,...,...,...,...,...,...
998,Construction Equipment & Supply,ces-co.net,Jeff Bryant,Jeff,Bryant,NaN,Email is Empty,pass,pass,pass,pass
999,Construction Equipment & Supply,ces-co.net,Paul Newland,Paul,Newland,NaN,Email is Empty,pass,pass,pass,pass
1000,Construction Equipment & Supply,ces-co.net,Randy Fulmer,Randy,Fulmer,NaN,Email is Empty,pass,pass,pass,pass
1001,Construction Equipment & Supply,ces-co.net,Edward Cordova,Edward,Cordova,NaN,Email is Empty,pass,pass,pass,pass
1002,Construction Equipment & Supply,ces-co.net,Billie Bryant Schultz,Billie,Bryant Schultz,NaN,Email is Empty,pass,pass,pass,pass

In [132]:
#creating a dataframe only for existing emails
email2 = email[email['checker'] != 'pass']
email2

,Company Name,URL,Contact,First Name,Last Name,Email,pattern_match,pattern,punctuation,domain,checker
0,All In One Security,all-in-one-security.com,Josh Armstrong,Josh,Armstrong,josh.armstrong@aiosecurity.com,"{'pattern_match': 'first_name_last_name', 'pun...",first_name_last_name,.,aiosecurity.com,first_name_last_name.aiosecurity.com
9,A Action Rents,aactionrents.com,Clayton Johnson,Clayton,Johnson,cjohnson@ur.com,"{'pattern_match': 'first_initial_last_name', '...",first_initial_last_name,None,ur.com,first_initial_last_nameNoneur.com
10,A Action Rents,aactionrents.com,Patrick Williams,Patrick,Williams,patrickw@aactionrents.com,"{'pattern_match': 'first_name_last_initial', '...",first_name_last_initial,None,aactionrents.com,first_name_last_initialNoneaactionrents.com
12,Acme Partyworks,acmepartyworks.com,Shawn Cummings,Shawn,Cummings,shawn.cummings@staples.com,"{'pattern_match': 'first_name_last_name', 'pun...",first_name_last_name,.,staples.com,first_name_last_name.staples.com
13,The A.J. Gates Company,ajgates.com,Frank Mezgec,Frank,Mezgec,frankm@ajgates.com,"{'pattern_match': 'first_name_last_initial', '...",first_name_last_initial,None,ajgates.com,first_name_last_initialNoneajgates.com
...,...,...,...,...,...,...,...,...,...,...,...
982,FSR,fsrinc.com,Jan Sandri,Jan,Sandri,jsandri@fsrinc.com,"{'pattern_match': 'first_initial_last_name', '...",first_initial_last_name,None,fsrinc.com,first_initial_last_nameNonefsrinc.com
984,FSR,fsrinc.com,Chaz Porter,Chaz,Porter,CPorter@fsrinc.com,"{'pattern_match': 'first_initial_last_name', '...",first_initial_last_name,None,fsrinc.com,first_initial_last_nameNonefsrinc.com
985,FSR,fsrinc.com,Felicia Heinis,Felicia,Heinis,fheinis@fsrinc.com,"{'pattern_match': 'first_initial_last_name', '...",first_initial_last_name,None,fsrinc.com,first_initial_last_nameNonefsrinc.com
993,Davis Distribution,davisdistribution.com,Jared Romanyak,Jared,Romanyak,jared@davisdistribution.com,"{'pattern_match': 'first_name', 'punct': None,...",first_name,None,davisdistribution.com,first_nameNonedavisdistribution.com
996,Davis Distribution,davisdistribution.com,Nate Taliani,Nate,Taliani,ntaliani@davisdistribution.com,"{'pattern_match': 'first_initial_last_name', '...",first_initial_last_name,None,davisdistribution.com,first_initial_last_nameNonedavisdistribution.com

In [133]:
#verifiying if the companies have their email with the checker 
valid = email2.groupby('Company Name')['checker'].nunique() ==1 
valid

Company Name
A Action Rents             False
A Ismn                      True
AAA Systems                False
AGCO                        True
AHC Appliance               True
                           ...
Woody Associates, Inc       True
Yerxa's Power Equipment     True
Z Systems                   True
Zimmer Biomet               True
discountplay                True
Name: checker, Length: 205, dtype: bool

In [134]:
valid["A Action Rents"]

False

In [135]:
test5 = "A Action Rents"
valid[f'{test5}']

False

In [136]:
def valid_company(string): 
    return valid[f'{string}']

In [137]:
# checking if there is an email provided or the email provided matches any of the patterns
def usable_company(company, pattern): 
    if pattern == 'Email is Empty': 
        return False
    elif pattern == 'Email given, pattern not found': 
        return False 
    else :
        return valid_company(f'{company}')

In [138]:
email['Usable'] = email[["Company Name","pattern_match"]].apply(lambda x: usable_company(*x), axis=1)
email

,Company Name,URL,Contact,First Name,Last Name,Email,pattern_match,pattern,punctuation,domain,checker,Usable
0,All In One Security,all-in-one-security.com,Josh Armstrong,Josh,Armstrong,josh.armstrong@aiosecurity.com,"{'pattern_match': 'first_name_last_name', 'pun...",first_name_last_name,.,aiosecurity.com,first_name_last_name.aiosecurity.com,True
1,All In One Security,all-in-one-security.com,Paul Jr Cox Sr.,Paul,Jr Cox Sr.,NaN,Email is Empty,pass,pass,pass,pass,False
2,ALL4,allinc.com,Kristiaan Wiedegreen,Kristiaan,Wiedegreen,NaN,Email is Empty,pass,pass,pass,pass,False
3,ALL4,allinc.com,Michael Gach,Michael,Gach,NaN,Email is Empty,pass,pass,pass,pass,False
4,Alarm Brokers,alarmbrokers.net,Ashley Newsom,Ashley,Newsom,NaN,Email is Empty,pass,pass,pass,pass,False
...,...,...,...,...,...,...,...,...,...,...,...,...
998,Construction Equipment & Supply,ces-co.net,Jeff Bryant,Jeff,Bryant,NaN,Email is Empty,pass,pass,pass,pass,False
999,Construction Equipment & Supply,ces-co.net,Paul Newland,Paul,Newland,NaN,Email is Empty,pass,pass,pass,pass,False
1000,Construction Equipment & Supply,ces-co.net,Randy Fulmer,Randy,Fulmer,NaN,Email is Empty,pass,pass,pass,pass,False
1001,Construction Equipment & Supply,ces-co.net,Edward Cordova,Edward,Cordova,NaN,Email is Empty,pass,pass,pass,pass,False
1002,Construction Equipment & Supply,ces-co.net,Billie Bryant Schultz,Billie,Bryant Schultz,NaN,Email is Empty,pass,pass,pass,pass,False